const sampleEntryTestData = {
    title: "IELTS Practice Test 3",
    description: "A comprehensive IELTS test focusing on environmental topics.",
    testType: "IELTS",
    totalTime: 180,
    sections: [
        {
            name: "Listening",
            description: "Listen to four recordings and answer questions",
            timeLimit: 40,
            passages: [
                {
                    text: "Audio transcript for Listening passage about renewable energy sources",
                    questions: [
                        {
                            type: "multipleChoice",
                            text: "What is the main topic of the lecture?",
                            options: [
                                {
                                    text: "Solar power",
                                    isCorrect: false
                                },
                                {
                                    text: "Wind energy",
                                    isCorrect: false
                                },
                                {
                                    text: "Renewable energy sources",
                                    isCorrect: true
                                },
                                {
                                    text: "Fossil fuels",
                                    isCorrect: false
                                }
                            ],
                            points: 1
                        },
                        {
                            type: "shortAnswer",
                            text: "What percentage of global electricity comes from renewable sources according to the speaker?",
                            correctAnswer: "26%",
                            points: 1
                        },
                        {
                            type: "trueFalse",
                            text: "The speaker suggests that all countries have equal potential for solar energy production.",
                            correctAnswer: false,
                            points: 1
                        },
                        {
                            type: "fillInTheBlank",
                            text: "Hydroelectric power is generated by harnessing the energy of flowing ____.",
                            correctAnswer: "water",
                            points: 1
                        },
                        {
                            type: "matching",
                            text: "Match the renewable energy source with its characteristic:",
                            matchingPairs: [
                                {
                                    left: "Solar",
                                    right: "Photovoltaic cells"
                                },
                                {
                                    left: "Wind",
                                    right: "Turbines"
                                },
                                {
                                    left: "Geothermal",
                                    right: "Earth's heat"
                                }
                            ],
                            points: 3
                        },
                        {
                            type: "selectFromDropdown",
                            text: "The country mentioned as a leader in geothermal energy production is [country].",
                            options: [
                                {
                                    text: "USA",
                                    isCorrect: false
                                },
                                {
                                    text: "China",
                                    isCorrect: false
                                },
                                {
                                    text: "Iceland",
                                    isCorrect: true
                                },
                                {
                                    text: "Germany",
                                    isCorrect: false
                                }
                            ],
                            points: 1
                        },
                        {
                            type: "ordering",
                            text: "Order the following renewable energy sources from most to least globally utilized, according to the lecture:",
                            orderItems: [
                                "Hydropower",
                                "Wind",
                                "Solar",
                                "Biomass"
                            ],
                            points: 2
                        },
                        {
                            type: "multipleChoice",
                            text: "Which of the following is NOT mentioned as a benefit of renewable energy?",
                            options: [
                                {
                                    text: "Reduced carbon emissions",
                                    isCorrect: false
                                },
                                {
                                    text: "Energy independence",
                                    isCorrect: false
                                },
                                {
                                    text: "Lower energy costs",
                                    isCorrect: false
                                },
                                {
                                    text: "Increased biodiversity",
                                    isCorrect: true
                                }
                            ],
                            points: 1
                        },
                        {
                            type: "shortAnswer",
                            text: "What term does the speaker use to describe energy sources that will eventually run out?",
                            correctAnswer: "Non-renewable",
                            points: 1
                        },
                        {
                            type: "trueFalse",
                            text: "The speaker suggests that renewable energy can completely replace fossil fuels in the near future.",
                            correctAnswer: false,
                            points: 1
                        }
                    ]
                }
            ]
        },
        {
            name: "Reading",
            description: "Read three passages and answer questions",
            timeLimit: 60,
            passages: [
                {
                    text: "Long text about the impact of plastic pollution on marine ecosystems.",
                    imageFile: null,
                    questions: [
                        {
                            type: "multipleChoice",
                            text: "What is the primary source of plastic pollution in oceans according to the passage?",
                            options: [
                                {
                                    text: "Industrial waste",
                                    isCorrect: false
                                },
                                {
                                    text: "Fishing nets",
                                    isCorrect: false
                                },
                                {
                                    text: "Single-use plastics",
                                    isCorrect: true
                                },
                                {
                                    text: "Microbeads",
                                    isCorrect: false
                                }
                            ],
                            points: 1
                        },
                        {
                            type: "trueFalse",
                            text: "The passage suggests that all plastics in the ocean eventually biodegrade.",
                            correctAnswer: false,
                            points: 1
                        },
                        {
                            type: "shortAnswer",
                            text: "What term is used to describe tiny plastic particles less than 5mm in size?",
                            correctAnswer: "Microplastics",
                            points: 1
                        },
                        {
                            type: "fillInTheBlank",
                            text: "The Great Pacific Garbage Patch is located in the ____ Ocean.",
                            correctAnswer: "Pacific",
                            points: 1
                        },
                        {
                            type: "matching",
                            text: "Match the marine animals with the plastic threats they face:",
                            matchingPairs: [
                                {
                                    left: "Sea turtles",
                                    right: "Mistaking plastic bags for jellyfish"
                                },
                                {
                                    left: "Seabirds",
                                    right: "Ingesting floating plastic pieces"
                                },
                                {
                                    left: "Whales",
                                    right: "Entanglement in fishing gear"
                                }
                            ],
                            points: 3
                        },
                        {
                            type: "selectFromDropdown",
                            text: "The passage states that by 2050, there could be more [item] than fish in the oceans by weight.",
                            options: [
                                {
                                    text: "Boats",
                                    isCorrect: false
                                },
                                {
                                    text: "Coral",
                                    isCorrect: false
                                },
                                {
                                    text: "Plastic",
                                    isCorrect: true
                                },
                                {
                                    text: "Seaweed",
                                    isCorrect: false
                                }
                            ],
                            points: 1
                        },
                        {
                            type: "ordering",
                            text: "Order the following steps in the plastic pollution cycle from beginning to end:",
                            orderItems: [
                                "Production of plastic items",
                                "Consumer use and disposal",
                                "Entry into waterways",
                                "Breakdown into microplastics"
                            ],
                            points: 2
                        },
                        {
                            type: "multipleChoice",
                            text: "Which of the following is NOT mentioned as a solution to plastic pollution?",
                            options: [
                                {
                                    text: "Recycling programs",
                                    isCorrect: false
                                },
                                {
                                    text: "Bans on single-use plastics",
                                    isCorrect: false
                                },
                                {
                                    text: "Beach clean-up initiatives",
                                    isCorrect: false
                                },
                                {
                                    text: "Increased plastic production",
                                    isCorrect: true
                                }
                            ],
                            points: 1
                        },
                        {
                            type: "shortAnswer",
                            text: "What percentage of all plastic ever produced has been recycled, according to the passage?",
                            correctAnswer: "9%",
                            points: 1
                        },
                        {
                            type: "trueFalse",
                            text: "The passage suggests that individual actions can have a significant impact on reducing plastic pollution.",
                            correctAnswer: true,
                            points: 1
                        }
                    ]
                }
            ]
        },
        {
            name: "Writing",
            description: "Complete two writing tasks",
            timeLimit: 60,
            questions: [
                {
                    type: "essay",
                    text: "Task 1: The graph below shows the percentage of households with access to the internet in four different countries between 2000 and 2020. Summarize the information by selecting and reporting the main features, and make comparisons where relevant.",
                    points: 20
                },
                {
                    type: "essay",
                    text: "Task 2: Some people believe that individuals cannot do anything to improve the environment and that only governments and large companies can make a difference. To what extent do you agree or disagree?",
                    points: 20
                }
            ]
        },
        {
            name: "Speaking",
            description: "Participate in a spoken interview",
            timeLimit: 20,
            questions: [
                {
                    type: "shortAnswer",
                    text: "Part 1: Let's talk about recycling. Do you recycle regularly? Why or why not?",
                    points: 5
                },
                {
                    type: "essay",
                    text: "Part 2: Describe a place you visited that made you feel relaxed. You should say: where it was, when you went there, what you did there, and explain why this place made you feel relaxed.",
                    points: 10
                },
                {
                    type: "shortAnswer",
                    text: "Part 3: Do you think it's important for people to take regular breaks from work or study? Why or why not?",
                    points: 5
                }
            ]
        }
    ]
};

export default sampleEntryTestData;